
services:
  - type: web
    name: planner-organiza
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python render_startup.py && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableWebsocketCompression=false --server.enableXsrfProtection=false --server.maxUploadSize=50
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false # Você precisa definir isso manualmente no dashboard do Render
      - key: JWT_SECRET
        sync: false # Você precisa definir isso manualmente no dashboard do Render
      - key: STRIPE_API_KEY
        sync: false # Adicione sua chave secreta do Stripe no dashboard do Render
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false # Adicione sua chave publicável do Stripe no dashboard do Render
      - key: FIREBASE_API_KEY
        sync: false # Adicione sua chave API do Firebase no dashboard do Render
      - key: FIREBASE_DATABASE_URL
        sync: false # Adicione o URL do seu banco de dados Firebase no dashboard do Render
    autoDeploy: true
    healthCheckPath: /_stcore/health
    plan: free # Você pode mudar para 'starter' se precisar de mais recursos

databases:
  - name: planner-db
    plan: free # Plano gratuito com 1GB de armazenamento 
    databaseName: planner
    user: planner_user
