[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""

[theme]
primaryColor = "#B8860B"
backgroundColor = "#1C1C1C"
secondaryBackgroundColor = "#2A2A2A"
textColor = "#F5F5F5"
font = "sans serif"
base = "dark"

[browser]
gatherUsageStats = false
serverAddress = "plannerorganiza.com.br"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
fastReruns = true

[ui]
hideTopBar = true
