[pages]
# Lista apenas as páginas que queremos mostrar na barra lateral
order = [
    "propostas.py",
    "clientes.py",
    "financeiro.py",
    "cadastros.py",
    "relatorios.py"
]

# Oculta todas as outras páginas
visibility = """
main.py = false
login.py = false
admin.py = false
mais.py = false
backup.py = false
contas_pagar.py = false
"""