[pages]
# Lista apenas as páginas que queremos mostrar na barra lateral
order = [
    "propostas.py",
    "clientes.py",
    "financeiro.py",
    "cadastros.py",
    "relatorios.py"
]

# Oculta todas as outras páginas
visibility = """
hidden = [
    "main.py",
    "admin.py",
    "backup.py",
    "contas_pagar.py",
    "fornecedores.py",
    "login.py",
    "mais.py"
]
"""